### ISSUE TITLE
Criar lançamento "automático" de horários semanais padronizados

### ISSUE THREAD

**Issue by thiagotrentin** [viniciusknob/queiroz.js#49]
Gostaria que existisse a funcionalidade de fazer o lançamento de horas de forma automática nos pedidos semanas.

Semanalmente faço o preenchimento dos horários que trabalhei, salvo raras exceções, sempre executo o horário padrão da companhia.

Seria mais produtivo ter um botão que preenche-se para mim a jornada diária, respeitando as regras da CLT e ignorando feriados.

É importante salientar que esses horários não poderiam ser britânicos, ou seja, ser sempre 08:30 - 12:00 e 13:00 - 18:18.

**Comment by viniciusknob** [comment]
Recurso implementado. Para utilizar, basta acessar o menu "hamburger" do dia em questão e clicar em Prencher Horários. Essa ação prenche o total de 4 horários criados dinamicamente, e considerando (neste momento) o limite total calculado de 8h. Os horários base são 08h30, 12h, 13h e 17h30, e a randomização faz os horários serem gerados "ao redor" desses horários base, sendo que:
- Para 08h30 a variação pode chegar em -5 até +5, ou seja, 08h25 e 08h35;
- Para 12h pode chegar a 11h55;
- Para 13h pode chegar a 13h05;
- E o último horário pode variar de acordo com os anteriores.

![image](https://user-images.githubusercontent.com/3440175/219692016-0a096328-71aa-4143-8b42-84c37bac94f5.png)
